// Auto-generated file - do not edit manually
// Generated by @smartbill/firestore-convex-style

export interface DataModel {
  // Add your data model types here
  // This is a placeholder - implement your actual data model
}

export type TableNames = keyof DataModel;
export type DocumentNames = DataModel[TableNames];
