// Auto-generated file - do not edit manually
// Generated by @smartbill/firestore-convex-style

export interface ServerFunctions {
  // Add your server functions here
  // This is a placeholder - implement your actual server functions
}

export type FunctionNames = keyof ServerFunctions;
